### ISSUE TITLE
Data miss

### ISSUE THREAD

**Issue by qianmingduowan** [shiyujiao/Sat2StrPanoramaSynthesis#2]
I find the data split file in Line 22: allDataList: "ACT_data.mat" Sat2StrPanoramaSynthesis/load_data/load_data_cvact.py can not found in you data share web: [https://anu365-my.sharepoint.com/personal/u6293587_anu_edu_au/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fu6293587%5Fanu%5Fedu%5Fau%2FDocuments%2Fdataset%2FForRelease%2FSat2StrPanoramaSynthesis&ga=1]
Is that file forget to  upload?

**Comment by shiyujiao** [comment]
Hi, thank you for discovering this problem. Please refer to "https://github.com/shiyujiao/IBL/script/OriNet_CVACT/CVACT_orientations/ACT_data.mat" to get the data.

**Comment by qianmingduowan** [comment]
Thanks for your kind!
